In [12]:
# Generate fake transaction data
import pandas as pd
from faker import Faker
import random

fake = Faker('id_ID')

n = 30  # number of rows
data = {
    'id_transaksi': [fake.uuid4() for _ in range(n)],
    'id_produk': [fake.random_int(min=1000, max=9999) for _ in range(n)],
    'jumlah': [random.randint(1, 10) for _ in range(n)],
    'harga_satuan': [random.randint(10000, 100000) for _ in range(n)],
    'tanggal_transaksi': [fake.date_between(start_date='-1y', end_date='today') for _ in range(n)]
}
# Custom transaction data as requested
data = {
    'id_transaksi': [f'TRX{str(i+1).zfill(3)}' for i in range(n)],
    'id_produk': [f'PROD-{chr(65 + (i % 3))}' for i in range(n)],  # PROD-A, PROD-B, PROD-C
    'jumlah': [random.randint(1, 10) for _ in range(n)],
    'harga_satuan': [random.randint(10000, 100000) for _ in range(n)],
    'tanggal_transaksi': [f'2025-05-{str((i % 31) + 1).zfill(2)}' for i in range(n)]
}
df = pd.DataFrame(data)
df.head()
# Update 'id_transaksi' to ensure it goes up to TRX030 and format 'tanggal_transaksi' to dd-mm-yyyy
df['id_transaksi'] = [f'TRX{str(i+1).zfill(3)}' for i in range(n)]
df['tanggal_transaksi'] = pd.to_datetime(df['tanggal_transaksi']).dt.strftime('%d-%m-%Y')
df.head()

df['tanggal_transaksi'] = '03-07-2025'
print(df)
# Update 'id_transaksi' to ensure it goes up to TRX030 and format 'tanggal_transaksi' to dd-mm-yyyy

df.to_csv('penjualan_2025-07-03.csv', index=False)

   id_transaksi id_produk  jumlah  harga_satuan tanggal_transaksi
0        TRX001    PROD-A       2         38878        03-07-2025
1        TRX002    PROD-B       8         27701        03-07-2025
2        TRX003    PROD-C       6         31379        03-07-2025
3        TRX004    PROD-A       7         29041        03-07-2025
4        TRX005    PROD-B       1         46361        03-07-2025
5        TRX006    PROD-C       7         96180        03-07-2025
6        TRX007    PROD-A       7         83192        03-07-2025
7        TRX008    PROD-B       8         39027        03-07-2025
8        TRX009    PROD-C      10         42262        03-07-2025
9        TRX010    PROD-A       8         95121        03-07-2025
10       TRX011    PROD-B       4         27891        03-07-2025
11       TRX012    PROD-C       2         34739        03-07-2025
12       TRX013    PROD-A       6         27126        03-07-2025
13       TRX014    PROD-B       4         11646        03-07-2025
14       TRX015    PROD-C       8         13926        03-07-2025
15       TRX016    PROD-A       2         85322        03-07-2025
16       TRX017    PROD-B       4         20956        03-07-2025
17       TRX018    PROD-C       9         70017        03-07-2025
18       TRX019    PROD-A       5         67917        03-07-2025
19       TRX020    PROD-B       2         56881        03-07-2025
20       TRX021    PROD-C       2         48790        03-07-2025
21       TRX022    PROD-A       4         96826        03-07-2025
22       TRX023    PROD-B       5         95632        03-07-2025
23       TRX024    PROD-C       2         13493        03-07-2025
24       TRX025    PROD-A       9         55537        03-07-2025
25       TRX026    PROD-B       1         26436        03-07-2025
26       TRX027    PROD-C      10         57623        03-07-2025
27       TRX028    PROD-A       8         18015        03-07-2025
28       TRX029    PROD-B       6         25045        03-07-2025
29       TRX030    PROD-C       3         61451        03-07-2025

In [14]:
# Generate fake transaction data
import pandas as pd
from faker import Faker
import random
import numpy as np

fake = Faker('id_ID')

n = 30  # number of rows
data = {
    'id_transaksi': [fake.uuid4() for _ in range(n)],
    'id_produk': [fake.random_int(min=1000, max=9999) for _ in range(n)],
    'jumlah': [random.randint(1, 10) for _ in range(n)],
    'harga_satuan': [random.randint(10000, 100000) for _ in range(n)],
    'tanggal_transaksi': [fake.date_between(start_date='-1y', end_date='today') for _ in range(n)]
}
# Custom transaction data as requested
data = {
    'id_transaksi': [f'TRX{str(i+1).zfill(3)}' for i in range(n)],
    'id_produk': [f'PROD-{chr(65 + (i % 3))}' for i in range(n)],  # PROD-A, PROD-B, PROD-C
    'jumlah': [random.randint(1, 10) for _ in range(n)],
    'harga_satuan': [random.randint(10000, 100000) for _ in range(n)],
    'tanggal_transaksi': [f'2025-05-{str((i % 31) + 1).zfill(2)}' for i in range(n)]
}
df = pd.DataFrame(data)
df.head()
# Update 'id_transaksi' to ensure it goes up to TRX030 and format 'tanggal_transaksi' to dd-mm-yyyy
df['id_transaksi'] = [f'TRX{str(i+1).zfill(3)}' for i in range(n)]
df['tanggal_transaksi'] = pd.to_datetime(df['tanggal_transaksi']).dt.strftime('%d-%m-%Y')
df.head()

df['tanggal_transaksi'] = '03-07-2025'
print(df)
# Update 'id_transaksi' to ensure it goes up to TRX030 and format 'tanggal_transaksi' to dd-mm-yyyy

# Introduce inconsistency in 'id_produk' and set some 'jumlah' values to empty (NaN)

# Make some 'id_produk' values inconsistent
df.loc[5, 'id_produk'] = 'prod-a'
df.loc[10, 'id_produk'] = 'prod-b'
df.loc[15, 'id_produk'] = 'prod-c'

# Set a few 'jumlah' values to NaN (missing)
df.loc[3, 'jumlah'] = np.nan
df.loc[12, 'jumlah'] = np.nan
df.loc[27, 'jumlah'] = np.nan

df.to_csv('penjualan_2025-07-03.csv', index=False)

   id_transaksi id_produk  jumlah  harga_satuan tanggal_transaksi
0        TRX001    PROD-A       3         86653        03-07-2025
1        TRX002    PROD-B       8         27843        03-07-2025
2        TRX003    PROD-C       8         73726        03-07-2025
3        TRX004    PROD-A       1         39648        03-07-2025
4        TRX005    PROD-B       4         18049        03-07-2025
5        TRX006    PROD-C      10         38823        03-07-2025
6        TRX007    PROD-A       7         51941        03-07-2025
7        TRX008    PROD-B       2         70892        03-07-2025
8        TRX009    PROD-C       5         62747        03-07-2025
9        TRX010    PROD-A       1         61061        03-07-2025
10       TRX011    PROD-B       1         85426        03-07-2025
11       TRX012    PROD-C       6         82953        03-07-2025
12       TRX013    PROD-A      10         51926        03-07-2025
13       TRX014    PROD-B       8         22260        03-07-2025
14       TRX015    PROD-C       1         11207        03-07-2025
15       TRX016    PROD-A       8         75572        03-07-2025
16       TRX017    PROD-B       1         97148        03-07-2025
17       TRX018    PROD-C       1         89048        03-07-2025
18       TRX019    PROD-A       1         12867        03-07-2025
19       TRX020    PROD-B       7         73586        03-07-2025
20       TRX021    PROD-C       7         77292        03-07-2025
21       TRX022    PROD-A       2         98173        03-07-2025
22       TRX023    PROD-B       4         81867        03-07-2025
23       TRX024    PROD-C       2         71676        03-07-2025
24       TRX025    PROD-A       5         85388        03-07-2025
25       TRX026    PROD-B       2         18854        03-07-2025
26       TRX027    PROD-C       8         49387        03-07-2025
27       TRX028    PROD-A       1         44452        03-07-2025
28       TRX029    PROD-B       5         96660        03-07-2025
29       TRX030    PROD-C       4         18900        03-07-2025